---
sensor:
  - platform: pmsx003
    # Default interval of updating every second, but changing to 30 seconds to extend life but keep fan spinning
    # PMS5003 https://esphome.io/components/sensor/pmsx003.html
    type: PMSX003
    uart_id: pms5003_uart
    pm_2_5:
      name: "PM 2.5"
      id: pm_2_5
      device_class: pm25  # Added to report properly to HomeKit
    pm_1_0:
      name: "PM 1.0"
      id: pm_1_0
      device_class: pm1  # Added to report properly to HomeKit
    pm_10_0:
      name: "PM 10.0"
      id: pm_10_0
      device_class: pm10  # Added to report properly to HomeKit
    pm_0_3um:
      name: "PM 0.3"
      id: pm_0_3um
      filters:
    update_interval: 30s

  - platform: aqi
    # https://esphome.io/components/sensor/aqi/
    name: "PM 2.5 AQI"
    id: pm_2_5_aqi
    pm_2_5: pm_2_5
    pm_10_0: pm_10_0
    calculation_type: AQI
